default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hitokoto_development


test:
  <<: *default
  database: hitokoto_test


production:
  <<: *default
  database: hitokoto_production
  username: hitokoto
  password: <%= ENV['HITOKOTO_DATABASE_PASSWORD'] %>
